// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: usermgt/authapi/v1/authapi.proto

package authapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthService_LoginService_FullMethodName          = "/usermgt.authapi.v1.AuthService/LoginService"
	AuthService_UpdatePasswordService_FullMethodName = "/usermgt.authapi.v1.AuthService/UpdatePasswordService"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	LoginService(ctx context.Context, in *LoginServiceRequest, opts ...grpc.CallOption) (*LoginServiceResponse, error)
	UpdatePasswordService(ctx context.Context, in *UpdatePasswordServiceRequest, opts ...grpc.CallOption) (*UpdatePasswordServiceResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) LoginService(ctx context.Context, in *LoginServiceRequest, opts ...grpc.CallOption) (*LoginServiceResponse, error) {
	out := new(LoginServiceResponse)
	err := c.cc.Invoke(ctx, AuthService_LoginService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdatePasswordService(ctx context.Context, in *UpdatePasswordServiceRequest, opts ...grpc.CallOption) (*UpdatePasswordServiceResponse, error) {
	out := new(UpdatePasswordServiceResponse)
	err := c.cc.Invoke(ctx, AuthService_UpdatePasswordService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	LoginService(context.Context, *LoginServiceRequest) (*LoginServiceResponse, error)
	UpdatePasswordService(context.Context, *UpdatePasswordServiceRequest) (*UpdatePasswordServiceResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) LoginService(context.Context, *LoginServiceRequest) (*LoginServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginService not implemented")
}
func (UnimplementedAuthServiceServer) UpdatePasswordService(context.Context, *UpdatePasswordServiceRequest) (*UpdatePasswordServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePasswordService not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_LoginService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LoginService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginService(ctx, req.(*LoginServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdatePasswordService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdatePasswordService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdatePasswordService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdatePasswordService(ctx, req.(*UpdatePasswordServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermgt.authapi.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginService",
			Handler:    _AuthService_LoginService_Handler,
		},
		{
			MethodName: "UpdatePasswordService",
			Handler:    _AuthService_UpdatePasswordService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermgt/authapi/v1/authapi.proto",
}
